language: go

install:
  - go get github.com/spf13/cobra
  - go get github.com/spf13/viper
  - go get github.com/fatih/color
  - go get github.com/xordataexchange/crypt/config

script: go test -v ./...
