apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kaigara.fullname" . }}
  labels:
{{ include "kaigara.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "kaigara.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image:  {{ template "kaigara.image" . }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}