# Default values for kaigara.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: rubykube/kaigara
  tag: latest
  pullPolicy: Always
service:
  name: kaigara
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
ingress:
  enabled: true
  hosts:
    - kaigara.org
    - www.kaigara.org
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    enabled: true