#!/bin/sh

set -e

case $1 in
  "execute")
    if [ ! -f "/var/lib/uhttpd/state" ]; then
      kaigara provision
    fi
    echo "Running ${2}"
    exec $2
    ;;

  "provision")
    for OPS in /opt/kaigara/operations/*.sh;do
      echo "Running operation: $OPS"
      $OPS
      touch /var/lib/uhttpd/state
    done
    ;;

  "render")
    cp /opt/kaigara/resources/$2 $3
    ;;

  *)
    echo "Error: Wrong argument" 1>&2
    echo "Usage: kaigara execute|provision|render" 1>&2
    exit 1
    ;;
esac
