#!/bin/bash

ARCH=$(uname -m)
case $ARCH in
  x86) ARCH="386";;
  x86_64) ARCH="amd64";;
  i686) ARCH="386";;
  i386) ARCH="386";;
esac

OS=$(uname | tr '[:upper:]' '[:lower:]')

# Use the GitHub API to find the latest version for this project.
LATEST_URL="https://api.github.com/repos/mod/kaigara/releases/latest"
if type "curl" > /dev/null; then
	TAG=$(curl -s $LATEST_URL | awk '/\"tag_name\":/{gsub( /[,\"]/,"", $2); print $2}')
fi

KAIGARA_TAR="kaigara-$OS-$ARCH-$TAG.tar.gz"
DOWNLOAD_URL="https://github.com/mod/kaigara/releases/download/$TAG/$KAIGARA_TAR"

KAIGARA_TMP=`mktemp -d -t kaigara`

wget $DOWNLOAD_URL -O $KAIGARA_TMP/kaigara
tar -xf /tmp/$KAIGARA_TAR -C $KAIGARA_TMP

sudo cp $KAIGARA_TMP/kaigara /usr/local/bin/kaigara

echo "Kaigara is now installed."
